---
- name: Install Vault
  shell: |
    yum install -y yum-utils
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    yum install -y vault

- name: Create Vault Config
  copy:
    dest: /etc/vault.d/vault.hcl
    content: |
      ui = true
      storage "file" {
        path = "/opt/vault/data"
      }
      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

- name: Create Vault Data Dir
  file:
    path: /opt/vault/data
    state: directory
    owner: vault
    group: vault

- name: Start Vault
  service:
    name: vault
    state: started
    enabled: yes
