---
- name: Setup Jenkins Server
  hosts: jenkins_server
  become: yes
  roles:
    - jenkins

- name: Setup DevOps Tools Server
  hosts: devops_tools_server
  become: yes
  roles:
    - harbor
    - vault


# inside terraform-ansible/ansible folder
# ansible all -m ping
# ansible-playbook -i inventory.ini site.yml
