---
- name: Setup Jenkins Server
  hosts: jenkins_server
  become: yes
  roles:
    - jenkins

- name: Setup DevOps Tools Server
  hosts: devops_tools_server
  become: yes
  roles:
    - harbor
    - vault


# inside terraform-ansible/ansible folder
# ansible all -m ping
# ansible-playbook -i inventory.ini site.yml
# ansible jenkins -i inventory.ini -m shell -a "java -version && git --version && node --version && aws --version && docker --version && systemctl status jenkins --no-pager" --become
# ansible devops -i inventory.ini -m shell -a "vault --version && systemctl status vault --no-pager" --become
